### ISSUE TITLE
Boolean value based plugins do not work with validation (in case of  `type`d selector values) and will fail with unexpected error

### ISSUE THREAD

**Issue by deadratfink** [massfords/ts-rsql-to-sql#10]
Actually, this bug was somehow masked by [Optional "boolean" configuration options checked by key-in-object could resolve to true if the key is set to undefined](https://github.com/massfords/ts-rsql-query/issues/8). Without new version 1.3.3 the validation of the `'true'` or `'false'` values for boolean based plugin (like `IsNullPlugin` / `=null=`) might not be detected for `type`d  selectors.

Of course, with proper tests in live-db context it could have been detected earlier. Unfortunately, I forgot to add some :-(

Now , with version 1.3.3 we get the proper error (even if `context = { // ..., lax: undefined }`), e.g.:

RSQL filter: `floors=null=true`

Code:

```typescript
// Our selector mapping
export const selectors: IRsqlSelectors = {
  // ...,
  floors: {
    sql: /* sql */ `pi.floors`,
    type: 'number',
  },
}
```
Response:

```json
// Our custom error response object, see `details.rsqlError` for the proper ts-rsql-query validation result failure
{
  "error": {
    "statusCode": 400,
    "code": "RSQL_TO_SQL",
    "message": "Invalid SQL, not parsable from passed RSQL (filter 'q' and/or sort 'sort' query param(s)))",
    "details": {
      "rsqlError": "bad selector value for \"floors\": \"true\" is not a number",
      "rsqlFilter": "floors=null=true"
    }
  }
}
```

That means, we need a mechanism in the plugin configuration to suppress the validation in case plugins have fixed value(s) like The boolean-based plugins have. Currently, I see two ways to fix this and it does not seem to be a big deal. Either fix I have in mind can correct the out-of-the-box plugins. But this will not be the case for boolean-based plugins others might have been written so far, which I doubt ;- )

### Alternative 1:

Add an optional `skipValidation` flag to `RsqlOperatorPlugin` and evaluate it on validation but skip if this is set.

Pro:
- Easy and explicit flag to disable validation

Con:
- Values must be validated in the `RsqlOperatorPlugin.invariant`. Anyway, this is done already for the out-of-the-box plugins and others can already utilize the `isBooleanValueInvariant` function which is exported by lib. So, not a real "Con".

### Alternative 2:

Add an optional `allowedValues` string array to `RsqlOperatorPlugin` and evaluate it on validation.

Pro:
- No need to check in `invariant` part (check is automatic and developer does not need to take care of)
- Values are clearly shown in plugin config (could also be a reusable exported constant, e.g.: `const BOOLEAN_PLUGIN_VALUES = ["true", "false"];`)

Con:
- ?

### Summary

- Both are easy fixes. 
- I will prepare two PRs to show both solutions, so we can compare easily what fits best.
- Although, it is some kind of bugfix, from my point of it would be safer to release a major version due to the potential incompatibilty.
- Live-DB will contain some unit tests for this fix.

**Comment by massfords** [comment]
>Although, it is some kind of bugfix, from my point of it would be safer to release a major version due to the potential incompatibilty.

I think you're the only one using this library ;)

If we ever get to a 3.0, we'll need a logo.

**Comment by deadratfink** [comment]
Ok, then I will use 1.3.4 and add a migration path note in Changelog.md.

Being honest, in my opinion if you use RSQL in a serious way, this lib is the way to go in the JS/TS context. At least, we are going to use it heavily in our RSQL-driven backend projects.

**Comment by deadratfink** [comment]
@massfords Please check PRs:

1. Alternative (`skipValidation`): https://github.com/massfords/ts-rsql-query/pull/11
2. Alternative (`allowedValues`): https://github.com/massfords/ts-rsql-query/pull/12

Actually, I would slightly tend to 2nd alternative because I think dealing with the allowed values is more strict for the developer to validate these (and somehow less code in the invariant section).
