### ISSUE TITLE
to-sql cuts last character of operand if it contains a trailing or a leading + trailing  '*'

### ISSUE THREAD

**Issue by deadratfink** [massfords/ts-rsql-to-sql#2]
Hi,

thx for this nice library. I found a small bug when it comes to parsing the operands with wildcards (src/llb/to-sql.ts, line 137 - 143) which affects:

1. leading and the trailing: `*foo*`
2. the trailing: `foo*`

Replacing `operand.length - 2` with `operand.length - 1` would solve this issue.

The small program shows this:

```typescript
/**
 *
 * @param operand
 */
function testmewrong(operand: string) {
  const leadingWildcard = operand.startsWith('*');
  const trailingWildcard = operand.endsWith('*');

  if (leadingWildcard && trailingWildcard) {
    console.log(`Both: %${operand.substring(1, operand.length - 2)}%`); // not correct
  } else if (leadingWildcard) {
    console.log(`Leading: %${operand.substring(1)}`);
  } else if (trailingWildcard) {
    console.log(`Trailing: ${operand.substring(0, operand.length - 2)}%`); // not correct
  }
}

testmewrong('*foo*');
testmewrong('*foo');
testmewrong('foo*');

// WRONG:
// Both: %fo%
// Leading: %foo
// Trailing: fo%

/**
 *
 * @param operand
 */
function testmecorrect(operand: string) {
  const leadingWildcard = operand.startsWith('*');
  const trailingWildcard = operand.endsWith('*');

  if (leadingWildcard && trailingWildcard) {
    console.log(`Both: %${operand.substring(1, operand.length - 1)}%`); // correct
  } else if (leadingWildcard) {
    console.log(`Leading: %${operand.substring(1)}`);
  } else if (trailingWildcard) {
    console.log(`Trailing: ${operand.substring(0, operand.length - 1)}%`); // correct
  }
}

testmecorrect('*foo*');
testmecorrect('*foo');
testmecorrect('foo*');

// CORRECT:
// Both: %foo%
// Leading: %foo
// Trailing: foo%
```

I have prepared a local bugfix branch (with fix and extended unit tests), but I cannot push it due to repo write access restrictions.

BTW, I am little bit confused, the repo shows v1.1.2 in package.json but v1.1.3 is published. Is this normal?

**Comment by massfords** [comment]
Thanks, I'll take a look at the bug.

I don't recall what state I left this in with respect to publishing releases. It's likely that I was trying to script the publish and it failed and I had to do it manually. I'll add this to the things to fix. I'll have time to look at this later tonight.
